from __future__ import annotations

import re


_SUITE_RELEASE_ID = "accounting-suite-2026-07-17"
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_MONTH = re.compile(r"^\d{4}-(?:0[1-9]|1[0-2])$")
_HALF_YEAR = re.compile(r"^\d{4}-H[12]$")
_PLAIN_DECIMAL = re.compile(r"^-?(?:0|[1-9]\d*)(?:\.\d+)?$")
_MIN_CALCULATION_PRECISION = 28
_MAX_CALCULATION_EXPONENT = 999_999_999

_TABLE_FIELDS = {
    "allocation_drivers": {
        "driver_id",
        "driver_quantity",
        "driver_share",
        "entity",
        "period",
        "pool_id",
        "project_id",
    },
    "allocation_pools": {
        "account_id",
        "currency",
        "driver_type",
        "entity",
        "period",
        "pool_id",
        "pool_name",
        "source_amount",
    },
    "allocation_results": {
        "allocated_amount",
        "allocation_id",
        "currency",
        "driver_id",
        "entity",
        "journal_id",
        "period",
        "pool_id",
        "project_id",
    },
    "bank_accounts": {
        "account_id",
        "account_number_masked",
        "bank_account_id",
        "bank_name",
        "currency",
        "entity",
    },
    "bank_transactions": {
        "amount",
        "bank_account_id",
        "bank_transaction_id",
        "counterparty_id",
        "currency",
        "description",
        "direction",
        "entity",
        "journal_id",
        "transaction_date",
    },
    "budgets": {
        "budget_id",
        "cost_budget",
        "currency",
        "entity",
        "hours_budget",
        "period",
        "project_id",
        "revenue_budget",
    },
    "cash_receipts": {
        "amount",
        "bank_account_id",
        "currency",
        "customer_id",
        "entity",
        "invoice_id",
        "journal_id",
        "receipt_date",
        "receipt_id",
    },
    "chart_of_accounts": {
        "account_code",
        "account_id",
        "account_name",
        "account_type",
        "active",
        "currency",
        "entity",
        "normal_balance",
    },
    "contract_amendments": {
        "amendment_id",
        "amount_change",
        "approval_date",
        "approved_by",
        "contract_id",
        "currency",
        "entity",
        "scope_change",
    },
    "contracts": {
        "billing_method",
        "contract_id",
        "contract_value",
        "currency",
        "customer_id",
        "end_date",
        "entity",
        "project_id",
        "signed_date",
        "start_date",
        "status",
    },
    "credit_notes": {
        "amount",
        "credit_note_id",
        "currency",
        "entity",
        "invoice_id",
        "issue_date",
        "journal_id",
        "reason",
    },
    "customers": {
        "business_number",
        "country_code",
        "credit_terms_days",
        "customer_id",
        "customer_name",
        "entity",
        "industry",
    },
    "departments": {
        "cost_center",
        "department_id",
        "department_name",
        "entity",
    },
    "direct_costs": {
        "amount",
        "cost_date",
        "cost_type",
        "currency",
        "direct_cost_id",
        "entity",
        "project_id",
        "source_row_id",
        "source_table",
    },
    "employee_assignments": {
        "allocation_percent",
        "assignment_id",
        "employee_id",
        "end_date",
        "entity",
        "project_id",
        "start_date",
    },
    "employees": {
        "active",
        "currency",
        "department_id",
        "employee_id",
        "employee_name",
        "entity",
        "hire_date",
        "job_title",
        "monthly_salary",
    },
    "forecasts": {
        "as_of_date",
        "currency",
        "entity",
        "forecast_cash_in",
        "forecast_cash_out",
        "forecast_cost",
        "forecast_id",
        "forecast_revenue",
        "project_id",
    },
    "indirect_costs": {
        "amount",
        "cost_date",
        "currency",
        "description",
        "entity",
        "indirect_cost_id",
        "journal_id",
        "pool_id",
    },
    "invoices": {
        "amount",
        "contract_id",
        "currency",
        "customer_id",
        "due_date",
        "entity",
        "invoice_id",
        "issue_date",
        "journal_id",
        "milestone_id",
        "project_id",
        "status",
        "subtotal",
        "tax",
    },
    "journal_headers": {
        "approved_at",
        "approver_id",
        "counterparty_id",
        "creator_id",
        "creator_role",
        "currency",
        "description",
        "economic_event_date",
        "entered_at",
        "entity",
        "journal_id",
        "period",
        "posting_date",
        "project_id",
        "sequence",
        "source_id",
        "source_type",
        "status",
    },
    "journal_lines": {
        "account_id",
        "credit",
        "currency",
        "debit",
        "entity",
        "journal_id",
        "line_id",
        "line_number",
        "period",
        "project_id",
    },
    "management_kpis": {
        "dimension_id",
        "dimension_type",
        "entity",
        "kpi_id",
        "metric_name",
        "period",
        "unit",
        "value",
    },
    "milestones": {
        "billing_amount",
        "completion_date",
        "currency",
        "due_date",
        "entity",
        "milestone_id",
        "milestone_name",
        "obligation_id",
        "project_id",
        "status",
    },
    "payable_aging": {
        "aging_bucket",
        "ap_item_id",
        "as_of_date",
        "currency",
        "entity",
        "original_amount",
        "outstanding_amount",
        "vendor_cost_id",
        "vendor_id",
    },
    "payroll_costs": {
        "amount",
        "currency",
        "employee_id",
        "entity",
        "hours",
        "journal_id",
        "payroll_cost_id",
        "payroll_period",
        "project_id",
    },
    "performance_obligations": {
        "allocated_price",
        "contract_id",
        "currency",
        "end_date",
        "entity",
        "obligation_id",
        "obligation_name",
        "progress_percent",
        "project_id",
        "satisfaction_method",
        "start_date",
    },
    "projects": {
        "budget_amount",
        "currency",
        "customer_id",
        "department_id",
        "end_date",
        "entity",
        "fixed_price",
        "project_id",
        "project_manager_employee_id",
        "project_name",
        "start_date",
        "status",
    },
    "receivable_aging": {
        "aging_bucket",
        "ar_item_id",
        "as_of_date",
        "currency",
        "customer_id",
        "entity",
        "invoice_id",
        "original_amount",
        "outstanding_amount",
    },
    "trial_balance": {
        "account_id",
        "closing",
        "control_subledger",
        "credit_turnover",
        "currency",
        "debit_turnover",
        "entity",
        "opening",
        "period",
        "prior_closing",
        "trial_balance_id",
    },
    "vendor_costs": {
        "amount",
        "cost_date",
        "currency",
        "direct_flag",
        "entity",
        "invoice_reference",
        "journal_id",
        "project_id",
        "service_category",
        "vendor_cost_id",
        "vendor_id",
    },
    "vendor_payments": {
        "amount",
        "bank_account_id",
        "currency",
        "entity",
        "journal_id",
        "payment_date",
        "payment_id",
        "vendor_cost_id",
        "vendor_id",
    },
    "vendors": {
        "business_number",
        "country_code",
        "entity",
        "payment_terms_days",
        "service_category",
        "vendor_id",
        "vendor_name",
    },
    "work_logs": {
        "approved_by",
        "currency",
        "employee_id",
        "entity",
        "hourly_cost",
        "hours",
        "labor_cost",
        "project_id",
        "work_date",
        "work_log_id",
    },
}
_DECIMAL_FIELDS = {
    "employees": {"monthly_salary"},
    "projects": {"fixed_price", "budget_amount"},
    "contracts": {"contract_value"},
    "contract_amendments": {"amount_change"},
    "performance_obligations": {"allocated_price", "progress_percent"},
    "milestones": {"billing_amount"},
    "invoices": {"subtotal", "tax", "amount"},
    "credit_notes": {"amount"},
    "cash_receipts": {"amount"},
    "vendor_payments": {"amount"},
    "bank_transactions": {"amount"},
    "receivable_aging": {"original_amount", "outstanding_amount"},
    "payable_aging": {"original_amount", "outstanding_amount"},
    "employee_assignments": {"allocation_percent"},
    "work_logs": {"hours", "hourly_cost", "labor_cost"},
    "payroll_costs": {"hours", "amount"},
    "vendor_costs": {"amount"},
    "direct_costs": {"amount"},
    "indirect_costs": {"amount"},
    "allocation_pools": {"source_amount"},
    "allocation_drivers": {"driver_quantity", "driver_share"},
    "allocation_results": {"allocated_amount"},
    "budgets": {"revenue_budget", "cost_budget", "hours_budget"},
    "forecasts": {
        "forecast_revenue",
        "forecast_cost",
        "forecast_cash_in",
        "forecast_cash_out",
    },
    "management_kpis": {"value"},
    "journal_lines": {"debit", "credit"},
    "trial_balance": {
        "prior_closing",
        "opening",
        "debit_turnover",
        "credit_turnover",
        "closing",
    },
}
_DATE_FIELDS = {
    "employees": {"hire_date"},
    "projects": {"start_date", "end_date"},
    "contracts": {"signed_date", "start_date", "end_date"},
    "contract_amendments": {"approval_date"},
    "performance_obligations": {"start_date", "end_date"},
    "milestones": {"due_date", "completion_date"},
    "invoices": {"issue_date", "due_date"},
    "credit_notes": {"issue_date"},
    "cash_receipts": {"receipt_date"},
    "vendor_payments": {"payment_date"},
    "bank_transactions": {"transaction_date"},
    "receivable_aging": {"as_of_date"},
    "payable_aging": {"as_of_date"},
    "employee_assignments": {"start_date", "end_date"},
    "work_logs": {"work_date"},
    "vendor_costs": {"cost_date"},
    "direct_costs": {"cost_date"},
    "indirect_costs": {"cost_date"},
    "forecasts": {"as_of_date"},
    "journal_headers": {"posting_date", "economic_event_date"},
}
_DATETIME_FIELDS = {"journal_headers": {"entered_at", "approved_at"}}
_PERIOD_FIELDS = {
    "allocation_pools": {"period"},
    "allocation_drivers": {"period"},
    "allocation_results": {"period"},
    "budgets": {"period"},
    "payroll_costs": {"payroll_period"},
    "management_kpis": {"period"},
    "journal_headers": {"period"},
    "journal_lines": {"period"},
    "trial_balance": {"period"},
}
_INTEGER_FIELDS = {
    "customers": {"credit_terms_days"},
    "vendors": {"payment_terms_days"},
    "journal_headers": {"sequence"},
    "journal_lines": {"line_number"},
}
_BOOLEAN_FIELDS = {
    "chart_of_accounts": {"active"},
    "employees": {"active"},
    "vendor_costs": {"direct_flag"},
}
_NULLABLE_FIELDS = {
    ("customers", "industry"),
    ("contract_amendments", "scope_change"),
    ("milestones", "completion_date"),
    ("invoices", "status"),
    ("bank_transactions", "description"),
    ("forecasts", "forecast_cash_out"),
}
_PRIMARY_KEYS = {
    "allocation_drivers": "driver_id",
    "allocation_pools": "pool_id",
    "allocation_results": "allocation_id",
    "bank_accounts": "bank_account_id",
    "bank_transactions": "bank_transaction_id",
    "budgets": "budget_id",
    "cash_receipts": "receipt_id",
    "chart_of_accounts": "account_id",
    "contract_amendments": "amendment_id",
    "contracts": "contract_id",
    "credit_notes": "credit_note_id",
    "customers": "customer_id",
    "departments": "department_id",
    "direct_costs": "direct_cost_id",
    "employee_assignments": "assignment_id",
    "employees": "employee_id",
    "forecasts": "forecast_id",
    "indirect_costs": "indirect_cost_id",
    "invoices": "invoice_id",
    "journal_headers": "journal_id",
    "journal_lines": "line_id",
    "management_kpis": "kpi_id",
    "milestones": "milestone_id",
    "payable_aging": "ap_item_id",
    "payroll_costs": "payroll_cost_id",
    "performance_obligations": "obligation_id",
    "projects": "project_id",
    "receivable_aging": "ar_item_id",
    "trial_balance": "trial_balance_id",
    "vendor_costs": "vendor_cost_id",
    "vendor_payments": "payment_id",
    "vendors": "vendor_id",
    "work_logs": "work_log_id",
}
_FOREIGN_KEYS = {
    "employees": (("department_id", "departments", "department_id"),),
    "bank_accounts": (("account_id", "chart_of_accounts", "account_id"),),
    "projects": (
        ("customer_id", "customers", "customer_id"),
        ("project_manager_employee_id", "employees", "employee_id"),
        ("department_id", "departments", "department_id"),
    ),
    "contracts": (
        ("customer_id", "customers", "customer_id"),
        ("project_id", "projects", "project_id"),
    ),
    "contract_amendments": (
        ("contract_id", "contracts", "contract_id"),
        ("approved_by", "employees", "employee_id"),
    ),
    "performance_obligations": (
        ("contract_id", "contracts", "contract_id"),
        ("project_id", "projects", "project_id"),
    ),
    "milestones": (
        ("project_id", "projects", "project_id"),
        ("obligation_id", "performance_obligations", "obligation_id"),
    ),
    "invoices": (
        ("customer_id", "customers", "customer_id"),
        ("contract_id", "contracts", "contract_id"),
        ("project_id", "projects", "project_id"),
        ("milestone_id", "milestones", "milestone_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "credit_notes": (
        ("invoice_id", "invoices", "invoice_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "cash_receipts": (
        ("customer_id", "customers", "customer_id"),
        ("invoice_id", "invoices", "invoice_id"),
        ("bank_account_id", "bank_accounts", "bank_account_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "vendor_payments": (
        ("vendor_id", "vendors", "vendor_id"),
        ("vendor_cost_id", "vendor_costs", "vendor_cost_id"),
        ("bank_account_id", "bank_accounts", "bank_account_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "bank_transactions": (
        ("bank_account_id", "bank_accounts", "bank_account_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "receivable_aging": (
        ("customer_id", "customers", "customer_id"),
        ("invoice_id", "invoices", "invoice_id"),
    ),
    "payable_aging": (
        ("vendor_id", "vendors", "vendor_id"),
        ("vendor_cost_id", "vendor_costs", "vendor_cost_id"),
    ),
    "employee_assignments": (
        ("employee_id", "employees", "employee_id"),
        ("project_id", "projects", "project_id"),
    ),
    "work_logs": (
        ("employee_id", "employees", "employee_id"),
        ("project_id", "projects", "project_id"),
        ("approved_by", "employees", "employee_id"),
    ),
    "payroll_costs": (
        ("employee_id", "employees", "employee_id"),
        ("project_id", "projects", "project_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "vendor_costs": (
        ("vendor_id", "vendors", "vendor_id"),
        ("project_id", "projects", "project_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "direct_costs": (("project_id", "projects", "project_id"),),
    "indirect_costs": (
        ("pool_id", "allocation_pools", "pool_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "allocation_pools": (("account_id", "chart_of_accounts", "account_id"),),
    "allocation_drivers": (
        ("pool_id", "allocation_pools", "pool_id"),
        ("project_id", "projects", "project_id"),
    ),
    "allocation_results": (
        ("pool_id", "allocation_pools", "pool_id"),
        ("project_id", "projects", "project_id"),
        ("driver_id", "allocation_drivers", "driver_id"),
        ("journal_id", "journal_headers", "journal_id"),
    ),
    "budgets": (("project_id", "projects", "project_id"),),
    "forecasts": (("project_id", "projects", "project_id"),),
    "journal_headers": (
        ("creator_id", "employees", "employee_id"),
        ("approver_id", "employees", "employee_id"),
        ("project_id", "projects", "project_id"),
    ),
    "journal_lines": (
        ("journal_id", "journal_headers", "journal_id"),
        ("account_id", "chart_of_accounts", "account_id"),
        ("project_id", "projects", "project_id"),
    ),
    "trial_balance": (("account_id", "chart_of_accounts", "account_id"),),
}
_DIRECT_SOURCE_TABLES = {
    "payroll_costs",
    "vendor_costs",
    "work_logs",
    "allocation_results",
}
_CASHFLOW_POPULATIONS = (
    "bank_reconciliations",
    "cash_items",
    "cash_transactions",
    "financing_bridges",
    "supplier_finance_programs",
    "receivables",
    "payables",
    "profit_cash_bridges",
    "counterparty_exposures",
    "receivable_transfers",
    "covenants",
    "mandatory_payments",
    "period_end_events",
    "forecasts",
    "liquidity_positions",
)
SUITE_RELEASE_ID = _SUITE_RELEASE_ID
SHA256_PATTERN = _SHA256
MONTH_PATTERN = _MONTH
HALF_YEAR_PATTERN = _HALF_YEAR
PLAIN_DECIMAL_PATTERN = _PLAIN_DECIMAL
MIN_CALCULATION_PRECISION = _MIN_CALCULATION_PRECISION
MAX_CALCULATION_EXPONENT = _MAX_CALCULATION_EXPONENT
TABLE_FIELDS = _TABLE_FIELDS
DECIMAL_FIELDS = _DECIMAL_FIELDS
DATE_FIELDS = _DATE_FIELDS
DATETIME_FIELDS = _DATETIME_FIELDS
PERIOD_FIELDS = _PERIOD_FIELDS
INTEGER_FIELDS = _INTEGER_FIELDS
BOOLEAN_FIELDS = _BOOLEAN_FIELDS
NULLABLE_FIELDS = _NULLABLE_FIELDS
PRIMARY_KEYS = _PRIMARY_KEYS
FOREIGN_KEYS = _FOREIGN_KEYS
DIRECT_SOURCE_TABLES = _DIRECT_SOURCE_TABLES
CASHFLOW_POPULATIONS = _CASHFLOW_POPULATIONS
